### ISSUE TITLE
Testing installation

### ISSUE THREAD

**Issue by makeabhishek** [nbouziani/physics-driven-ml#2]
Hi Nacime,
Executing following 
```
cd physics_driven_ml
pytest tests
```
`ERROR: file or directory not found: tests`

If I run the command `pytest tests` from directory 'physics-driven-ml'. It is giving me farrowing error.
```

_______________ ERROR collecting tests/test_pytorch_coupling.py ________________
ImportError while importing test module '/Users/asaini/physics-driven-ml/tests/test_pytorch_coupling.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pytorch_coupling.py:3: in <module>
    import torch
E   ModuleNotFoundError: No module named 'torch'
=========================== short test summary info ============================
ERROR tests/test_pytorch_coupling.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.03s ===============================
```

**Comment by nbouziani** [comment]
Hi Abhishek,

- Regarding testing, there is a typo in the testing instructions which I have just fixed, it should be: 

```
cd physics-driven-ml 
```

- It looks like `torch` is not installed. Have you installed PyTorch within your Firedrake virtual environment as outlined in the setup section (cf. [setup instructions](https://github.com/nbouziani/physics-driven-ml#installing-pytorch))?

**Comment by makeabhishek** [comment]
Yes I installed the PyTorch. I tried it again. The messages ae shown below

```
(firedrake) asaini@pn2301151 ~ % conda install pytorch torchvision torchaudio -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(firedrake) asaini@pn2301151 ~ % pip install -e physics-driven-ml 
Obtaining file:///Users/asaini/physics-driven-ml
Requirement already satisfied: tqdm in ./firedrake/lib/python3.9/site-packages (from physics-driven-ml==1.0) (4.65.0)
Installing collected packages: physics-driven-ml
  Attempting uninstall: physics-driven-ml
    Found existing installation: physics-driven-ml 1.0
    Uninstalling physics-driven-ml-1.0:
      Successfully uninstalled physics-driven-ml-1.0
  Running setup.py develop for physics-driven-ml
Successfully installed physics-driven-ml-1.0
WARNING: You are using pip version 21.2.4; however, version 23.0.1 is available.
You should consider upgrading via the '/Users/asaini/firedrake/bin/python3 -m pip install --upgrade pip' command.
(firedrake) asaini@pn2301151 ~ % pytest tests
============================= test session starts ==============================
platform darwin -- Python 3.9.6, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/asaini
collected 0 items                                                              

============================ no tests ran in 0.00s =============================
ERROR: file or directory not found: tests

(firedrake) asaini@pn2301151 ~ % 
```
Furthermore, if I'm following the instructions its again giving me errors. I installed PyTorch but not sure why its giving error.

```
(firedrake) asaini@pn2301151 ~ % cd physics-driven-ml 
(firedrake) asaini@pn2301151 physics-driven-ml % cd physics_driven_ml/dataset_processing
(firedrake) asaini@pn2301151 dataset_processing % python generate_data.py --forward heat --ntrain 500 --ntest 50 --dataset_name heat_conductivity_500
Traceback (most recent call last):
  File "/Users/asaini/physics-driven-ml/physics_driven_ml/dataset_processing/generate_data.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
(firedrake) asaini@pn2301151 dataset_processing % python3
Python 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>> 
```

**Comment by makeabhishek** [comment]
It looks like there is issue with installing PyTorch for Mac M1 Max chip. I need to depreciate the python package to 3.7.

**Comment by nbouziani** [comment]
Hmm that's strange, `numpy` should already be installed within the Firedrake environment. I can see that there are some issues with using conda (see [here](https://www.firedrakeproject.org/download.html#system-anti-requirements)). Could you please try to use `pip` ?

Also, have you checked your firedrake installation ? You can do so by running:

```
cd $VIRTUAL_ENV/src/firedrake
pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection"
```
